# Generated by Django 3.2.16 on 2022-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='talab_raqami',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
